language: node_js
node_js:
- 7.8
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'baseheight.martinmetodiev.com' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: W+qEkvbk6y3kw9diXAaPAQwP99Ji5ROQbLf+TrmZE81r0RgxoJNJp0zygjMy+q1xLcboaCaM6T8m+DzGhf6FshlqiGn4eaIae7hbr5fi9vEcc9+DfDCxryw1ACrkl5/fTbDNRcLd8A3/DF1btd2ByMfDA/w2BDCYz1CS0cx8s2ot0ix+PNBTsOzc6m/oXeGz22okPnnKePGxmuqQQqInMM2gPL7VzjYAN1CbOHEXVcLSSdibh9APQcwShhe5l2Kq91c5J2UUbj8oj/VdCwod33BkeMQJl8TWGxjgsAf6AqXr6IAM3kv6CAM0jPLmbxzNQZfj7DVRYqafH9Xut3ZRBzbj5KmFdmIVUAE+Rzw0/BnT7K2sMtzrgKlB6ys8uECya0JmFk3EG3eO9WBzy603qX9+5rZL87zASUdWbPBqy8/382BnaQgaolSLo2ZmSRd3pdI//hjHt+MF2izwtCg5vCnj0nf5uU8QuDcl1ByvX9PprbkJXak+5r0QUewZAXLOig022EsOQqhkQQVRwaNuY7uBiXdoW60T978027R5Da5liopAxS8SqKspmy+NXnAwdSlphP62/dm2UQ+8ju+haigqgeUmxWzUWIbbjYUjU947lKd30w4MoUo5w25u9BblODlFBCI3c46EvxKsUGiYQ49zkKHQG52L3NCSkH03Nb4=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: 0HqUHiOZWRhAp5fON1ihm22Crp9CZYTSRMDTft59koiUFJyAzO5jKUBkTjf7ckCJvplC1U5y345jc0IUxX9MoNhZ2iAIZc16k673KuiN8SV5bLov3ujKLL6am46jOptWH49P8ik1vmTjdUv7ne+mYuNPM3w2CAZoeZD1XbsghMrE3fP+2PjHdLYHioO02AZ+1wvNCUKi1kSLBGWnSo9xaXeIW+fkk2mSmXexG1DfosAxMEc+T7PKyHeWS2KNzfK8umUJzHG4iHaiNwp1tL5pcESfLoUmY4zyH7nn5Sk0my0Nw7Vjnr5lAOXO+rG3X52Fin5tDgES9OyO0esXdQJ97OJwgbE+whHCpwlvoiDhmYm0H5VS2Z5oV3POQVFrw3R++ylG/SmRFd9ebHAjCtwX5AhtIOjK9S2EoKqzSzA72IkdQsPngFjiHjR2ntVD+FpFC6O6YZ1axFf0zJgf6LizjceXn7JY92bZMpqforD8IaUdO/dzdlUlZ4JuF+6STU0pfhqZIRdeWMDoZJ6ExwVT51mil7Qls+7PQuybNsoSboauuUIsb7yvlZ47UYt1ipHum+PfJ6Oibnl5q4y1aC4PJyjr1inB5Rl7exdBXx2XyADRd+V9FGKjpjCWrJS3OhHHrF9symyoF7OBySG+k8YtKWRv8o3CmX3tDHZOvMuVuC8=
  on:
    tags: true
- provider: releases
  api_key:
    secure: 0HqUHiOZWRhAp5fON1ihm22Crp9CZYTSRMDTft59koiUFJyAzO5jKUBkTjf7ckCJvplC1U5y345jc0IUxX9MoNhZ2iAIZc16k673KuiN8SV5bLov3ujKLL6am46jOptWH49P8ik1vmTjdUv7ne+mYuNPM3w2CAZoeZD1XbsghMrE3fP+2PjHdLYHioO02AZ+1wvNCUKi1kSLBGWnSo9xaXeIW+fkk2mSmXexG1DfosAxMEc+T7PKyHeWS2KNzfK8umUJzHG4iHaiNwp1tL5pcESfLoUmY4zyH7nn5Sk0my0Nw7Vjnr5lAOXO+rG3X52Fin5tDgES9OyO0esXdQJ97OJwgbE+whHCpwlvoiDhmYm0H5VS2Z5oV3POQVFrw3R++ylG/SmRFd9ebHAjCtwX5AhtIOjK9S2EoKqzSzA72IkdQsPngFjiHjR2ntVD+FpFC6O6YZ1axFf0zJgf6LizjceXn7JY92bZMpqforD8IaUdO/dzdlUlZ4JuF+6STU0pfhqZIRdeWMDoZJ6ExwVT51mil7Qls+7PQuybNsoSboauuUIsb7yvlZ47UYt1ipHum+PfJ6Oibnl5q4y1aC4PJyjr1inB5Rl7exdBXx2XyADRd+V9FGKjpjCWrJS3OhHHrF9symyoF7OBySG+k8YtKWRv8o3CmX3tDHZOvMuVuC8=
  skip_cleanup: true
  on:
    tags: true
