language: node_js
node_js:
- 10
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'baseheight.metodiev.dev' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: W+qEkvbk6y3kw9diXAaPAQwP99Ji5ROQbLf+TrmZE81r0RgxoJNJp0zygjMy+q1xLcboaCaM6T8m+DzGhf6FshlqiGn4eaIae7hbr5fi9vEcc9+DfDCxryw1ACrkl5/fTbDNRcLd8A3/DF1btd2ByMfDA/w2BDCYz1CS0cx8s2ot0ix+PNBTsOzc6m/oXeGz22okPnnKePGxmuqQQqInMM2gPL7VzjYAN1CbOHEXVcLSSdibh9APQcwShhe5l2Kq91c5J2UUbj8oj/VdCwod33BkeMQJl8TWGxjgsAf6AqXr6IAM3kv6CAM0jPLmbxzNQZfj7DVRYqafH9Xut3ZRBzbj5KmFdmIVUAE+Rzw0/BnT7K2sMtzrgKlB6ys8uECya0JmFk3EG3eO9WBzy603qX9+5rZL87zASUdWbPBqy8/382BnaQgaolSLo2ZmSRd3pdI//hjHt+MF2izwtCg5vCnj0nf5uU8QuDcl1ByvX9PprbkJXak+5r0QUewZAXLOig022EsOQqhkQQVRwaNuY7uBiXdoW60T978027R5Da5liopAxS8SqKspmy+NXnAwdSlphP62/dm2UQ+8ju+haigqgeUmxWzUWIbbjYUjU947lKd30w4MoUo5w25u9BblODlFBCI3c46EvxKsUGiYQ49zkKHQG52L3NCSkH03Nb4=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: Mtsv1DMRwBrikMsLpDtWTdty59JX6AA+woIl4KU43GWJhfZ6YYsTF6NDloKnuU1ZalCiybxIqWQVj1WM77aLyJCWRuhiVI7DLtiEwHL0jJYCJHQWiWBo6s8hv5juTnGlsl/gH+bxuV6r29HMeEPLxA+9uq9qXYXRCLmFOZ8khLTesr6aqZ+MR6Z+RKw2+dMm+R6kfNJXy1YAMG2px6BHSHaky+T9NAXNDUe7rkupCRqYbKgyibSHkrqJEYG7LY2+YqpF8/tNW3Aa5VZFPKUXezulZDqFZKy0xGwR5hF+nRxLI3mH9cLqvh5+QbNaLnuuGbr7nnCxQGNmn4KpM1DCO+rAbA07ZJDkzyHh4bGgLVEiRqmlUvRMMqrmD5ejaY4d9OU1yW+ABUqXwYnTCk7pxfvme3UO4EcnI/igK0bY1lVwty95u9Hp2bY08CvPMxx2EaHpl6uVDPUv8mwNCPCwbCeKDaKAsl5euyaQep+baD8goyrZ/M+w4kBUWPvTXEqriPj6vn4MgVzvzV2G+UFt/cxghrZEQn76IK2HxwzLyLZmajHy4M7/ZOlIiNRxaB9d1mvcmzH/Eocx6dLU8eioBszipBFF/WtglV+49pZpBn/EXV8E9rCgJLtbXSRKd7e/7vjmqsbqaNNVA0Sc3yGjnXyJQgEXm7tIsCNmc4EyNP8=
  on:
    tags: true
- provider: releases
  api_key:
    secure: Mtsv1DMRwBrikMsLpDtWTdty59JX6AA+woIl4KU43GWJhfZ6YYsTF6NDloKnuU1ZalCiybxIqWQVj1WM77aLyJCWRuhiVI7DLtiEwHL0jJYCJHQWiWBo6s8hv5juTnGlsl/gH+bxuV6r29HMeEPLxA+9uq9qXYXRCLmFOZ8khLTesr6aqZ+MR6Z+RKw2+dMm+R6kfNJXy1YAMG2px6BHSHaky+T9NAXNDUe7rkupCRqYbKgyibSHkrqJEYG7LY2+YqpF8/tNW3Aa5VZFPKUXezulZDqFZKy0xGwR5hF+nRxLI3mH9cLqvh5+QbNaLnuuGbr7nnCxQGNmn4KpM1DCO+rAbA07ZJDkzyHh4bGgLVEiRqmlUvRMMqrmD5ejaY4d9OU1yW+ABUqXwYnTCk7pxfvme3UO4EcnI/igK0bY1lVwty95u9Hp2bY08CvPMxx2EaHpl6uVDPUv8mwNCPCwbCeKDaKAsl5euyaQep+baD8goyrZ/M+w4kBUWPvTXEqriPj6vn4MgVzvzV2G+UFt/cxghrZEQn76IK2HxwzLyLZmajHy4M7/ZOlIiNRxaB9d1mvcmzH/Eocx6dLU8eioBszipBFF/WtglV+49pZpBn/EXV8E9rCgJLtbXSRKd7e/7vjmqsbqaNNVA0Sc3yGjnXyJQgEXm7tIsCNmc4EyNP8=
  skip_cleanup: true
  on:
    tags: true
